title: Heric Libong Dev Factory
email: hericlibong@gmail.com
description: >- 
  This is Heric Libong's personal Website.
baseurl: "/portfolio" # This is the subpath of your site, e.g. /blog
url: "https://hericlibong.github.io" # This is your site's domain name, e.g. jekyllrb.com
# twitter_username: jekyllrb
github_username: hericlibong

# Build settings
theme: minima


plugins:
  - jekyll-feed

# Navigation links
header_pages:
  - about.markdown
  - index.markdown

# Include post with future date
future: true



